const adminUsersPage = require('../../support/pageObjects/LMS/adminUsersPage')
const adminDashboardPage = require('../../support/pageObjects/LMS/adminDashboardPage')
const teacherOverViewPage = require('../../support/pageObjects/LMS/teacherOverViewPage')
const teacherDashboardPage = require('../../support/pageObjects/LMS/teacherDashboardPage')
const login = require('../../support/pageObjects/LMS/adminIndexPage')

const dayjs = require('dayjs')

describe("Admin Users Validation", function () {

    beforeEach(function () {
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
        cy.visit(Cypress.env("url"))
        cy.viewport(1920, 1080)
        cy.fixture("LMS/Credentials").then(function (validAdminLoginData) {
            cy.adminLogin(validAdminLoginData.username, validAdminLoginData.password)
        })
        cy.fixture("LMS/TeacherDetails.json").as('techerDetails')
        cy.fixture("LMS/Admin_StudentDetails.json").as('studentDetails')
    })
    it('TC_Student_007 Verify that School admin can add Students successfully when entered a valid data', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersStudentTab().click()
        cy.reload()
        adminUsersPage.getStudentSearchTxtfld().should('be.visible')
        adminUsersPage.getAddtudentBtn().click()
        adminUsersPage.getStudentFullNameTxtFld().type(this.studentDetails.studentName)
        adminUsersPage.getStudentGenderDropDown().click()
        adminUsersPage.getStudentGenderDropDownOpt().first().click()
        adminUsersPage.getStudentContactNumberTxtFld().type(this.studentDetails.studentContactNumber)
        adminUsersPage.getStudentRelationDropDown().click()
        adminUsersPage.getStudentRelationDropDownOpt().first().click()
        adminUsersPage.getStudentGurdianNameTxtFld().type(this.studentDetails.StudentFatherName)
        adminUsersPage.getStudentGurdianContactNumberTxtFld().type(this.studentDetails.studentFatherContactNumber)
        adminUsersPage.getStudentAddressTxtFld().type(this.studentDetails.studentAddress)
        adminUsersPage.getStudentPinecodeTxtFld().type(this.studentDetails.studentPinecode)
        adminUsersPage.getAddStudentBtn().click()
        cy.wait(2000)
        adminUsersPage.getStudentAcademicDetailsAmissionYearTxtFld().type(dayjs().format('YYYY'), { force: true })
        adminUsersPage.getStudentAcademicDetailsAdmissionNumberTxtFld().type(this.studentDetails.studentAddmissionNumber).wait(2000)
        adminUsersPage.getStudentAcademicDetailsGradeDropdown().click({ force: true })
        adminUsersPage.getStudentAcademicDetailsGradeDropdownOpt(this.studentDetails.studentGrade).click()
        adminUsersPage.getStudentAcademicDetailsSectionsDropdown().click({ force: true })
        adminUsersPage.getStudentAcademicDetailsSectionDropdownOpt().first().click()
        adminUsersPage.getStudentAcademicDetailsRollNoTxtFld().type(this.studentDetails.studentRollNo)
        adminUsersPage.getAddStudentBtn().click().wait(2000)
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentDeleteAccountBtn().click()
        adminUsersPage.getStudentConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Student_008 Verify that School admin can bulk upload students successfully', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersStudentTab().click()
        ,cy.reload()
        adminUsersPage.getStudentSearchTxtfld().should('be.visible')
        adminUsersPage.getStudentBulkUploadBtn().click()
        cy.contains('Specify Grade & Section to Add Students').should('be.visible')
        adminUsersPage.getAddStudentGradeDropdown().click()
        adminUsersPage.getAddStudentGradeDropdownOpt(this.studentDetails.studentGrade).click()
        adminUsersPage.getAddStudentSectionDropdown().click()
        adminUsersPage.getAddStudentSectionDropdownOpt(this.studentDetails.studentSection).click()
        adminUsersPage.getAddStudentDoneBtn().click()
        cy.contains('Upload Student Account in bulk').should('be.visible')
        adminUsersPage.getStudentBulkUploadDownloadSampleFile().should('be.visible')
        adminUsersPage.getStudentUploadStudentAccountsinbulkSelectFileFromComputerBtn().selectFile('cypress/fixtures/LMS/users_Student_23-05-2023 10_25_49.xlsx', { force: true })
        adminUsersPage.getStudentUploadStudentAccountsinbulkImportStudentAccounts().should('be.visible', { timeout: 2000 }).click()
        cy.contains('Student Account Imported successfully').should('be.visible')
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentDeleteAccountBtn().click()
        adminUsersPage.getStudentConfermationPopupDeleteBtn().click().wait(2000)
    })

    it('TC_Student_009 Verify that School admin can Edit the student details successfully', function () {
        adminUsersPage.getAdminUsersSideMenuTab().click({ force: true })
        adminUsersPage.getAdminUsersTeachersTab().click()
        adminUsersPage.getAdminUsersStudentTab().click()
        cy.reload()
        adminUsersPage.getStudentSearchTxtfld().should('be.visible')
        adminUsersPage.getStudentBulkUploadBtn().click()
        cy.contains('Specify Grade & Section to Add Students').should('be.visible')
        adminUsersPage.getAddStudentGradeDropdown().click()
        adminUsersPage.getAddStudentGradeDropdownOpt(this.studentDetails.studentGrade).click()
        adminUsersPage.getAddStudentSectionDropdown().click()
        adminUsersPage.getAddStudentSectionDropdownOpt(this.studentDetails.studentSection).click()
        adminUsersPage.getAddStudentDoneBtn().click()
        cy.contains('Upload Student Account in bulk').should('be.visible')
        adminUsersPage.getStudentBulkUploadDownloadSampleFile().should('be.visible')
        adminUsersPage.getStudentUploadStudentAccountsinbulkSelectFileFromComputerBtn().selectFile('cypress/fixtures/LMS/users_Student_23-05-2023 10_25_49.xlsx', { force: true })
        adminUsersPage.getStudentUploadStudentAccountsinbulkImportStudentAccounts().should('be.visible', { timeout: 2000 }).click()
        cy.contains('Student Account Imported successfully').should('be.visible')
        adminUsersPage.getStudentEditBtn(this.studentDetails.student).should('be.visible')
        adminUsersPage.getStudentViewBtn(this.studentDetails.student).should('be.visible')
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).should('be.visible')
        adminUsersPage.getStudentEditBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentEditSaveChangesBtn().click().wait(2000)
        adminUsersPage.getAdminAddNewTeacherAccountAcademicDetailsSaveChangesBtn().click({ force: true })
        adminUsersPage.getStudentDeleteBtn(this.studentDetails.student).click()
        adminUsersPage.getStudentDeleteAccountBtn().click()
        adminUsersPage.getStudentConfermationPopupDeleteBtn().click().wait(2000)
    })
})